[[redirects]]
  from = "/api*"
  to = "https://api.myuniroomies.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

  [[redirects]]
  from = "/activation/*"
  to = "https://myuniroomies.com/activation/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

  
  [[redirects]]
  from = "*"
  to = "https://myuniroomies.com"
  status = 200
  force = true
